# Generated by Django 4.1.3 on 2022-12-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='이름')),
                ('price_per_night', models.PositiveIntegerField(help_text='양수만 됩니다.', verbose_name='가격')),
                ('description', models.TextField()),
                ('address', models.CharField(help_text='주소 기입', max_length=140, verbose_name='주소')),
                ('pets_allowed', models.BooleanField(default=True, help_text='애완 동물 반입 여부', verbose_name='애완 동물 가능?')),
            ],
        ),
    ]
